#### simulation1 ####
library(mvtnorm)
library(moments)
library(MomTrunc)
library(cubature)
library(mvtnorm)
library(GIGrvg)
library(ghyp)
source(paste(WD.PATH, 'function/rMNIG_rMSL.R', sep=''))
source(paste(WD.PATH, 'function/MCFA.na.R', sep=''))
source(paste(WD.PATH, 'function/MCtFA.na.R', sep=''))
source(paste(WD.PATH, 'function/MCrstFA.na.R', sep=''))
source(paste(WD.PATH, 'function/initial.R', sep=''))
source(paste(WD.PATH, 'function/gener_na.R', sep=''))
n=500
p=3
g=2
q=2
true.clus = c(rep(1,n),rep(2,n))
nu = c(2,3)
alpha = matrix(c(-5,-7,-7,-5,7,7),p,g)
ww = c(0.5,0.5)
mu = matrix(c(1,5,5,1,1,3), p, g)
sig = array(NA, dim=c(p,p,g))
sig[,,1] = rbind(c(4,-1.8,-1), c(-1.8, 2, 0.9), c(-1, 0.9,2))
sig[,,2] = rbind(c(4,1.8,0.8), c(1.8, 2, 0.5), c(0.8, 0.5, 2))

#rMNIG
for(j in 1:m)
{
  Y=NULL
  for(i in 1:g)
  {
    Y <- rbind(Y, rMNIG(n, mu[,i], sig[,,i], alpha[,i], nu[i]))
  }
  initial=init.para(Y=Y,g=g,q=q,true.clus=true.clus,init='CPC',init.clus=T,random.start=F)
  Y.na1=gener.na(Y,0.1)
  Y.na2=gener.na(Y,0.2)
  Y.na3=gener.na(Y,0.3)
  Y.na4=gener.na(Y,0.4)
  fit.n.na1=MCFA.na.ECME(Y.na=Y.na1,initial=initial,true.clus=true.clus,eqnu=F,tol=1e-6,max.iter=2000,per=100)
  fit.t.na1=MCtFA.na.ECME(Y.na=Y.na1,initial=initial,true.clus=true.clus,eqnu=F,tol=1e-6,max.iter=2000,per=100)
  fit.rst.na1=MCrstFA.na.ECME(Y.na=Y.na1,initial=initial,true.clus=true.clus,eqnu=F,tol=1e-6,max.iter=2000,per=100)
  fit.n.na2=MCFA.na.ECME(Y.na=Y.na2,initial=initial,true.clus=true.clus,eqnu=F,tol=1e-6,max.iter=2000,per=100)
  fit.t.na2=MCtFA.na.ECME(Y.na=Y.na2,initial=initial,true.clus=true.clus,eqnu=F,tol=1e-6,max.iter=2000,per=100)
  fit.rst.na2=MCrstFA.na.ECME(Y.na=Y.na2,initial=initial,true.clus=true.clus,eqnu=F,tol=1e-6,max.iter=2000,per=100)
  fit.n.na3=MCFA.na.ECME(Y.na=Y.na3,initial=initial,true.clus=true.clus,eqnu=F,tol=1e-6,max.iter=2000,per=100)
  fit.t.na3=MCtFA.na.ECME(Y.na=Y.na3,initial=initial,true.clus=true.clus,eqnu=F,tol=1e-6,max.iter=2000,per=100)
  fit.rst.na3=MCrstFA.na.ECME(Y.na=Y.na3,initial=initial,true.clus=true.clus,eqnu=F,tol=1e-6,max.iter=2000,per=100)
  fit.n.na4=MCFA.na.ECME(Y.na=Y.na4,initial=initial,true.clus=true.clus,eqnu=F,tol=1e-6,max.iter=2000,per=100)
  fit.t.na4=MCtFA.na.ECME(Y.na=Y.na4,initial=initial,true.clus=true.clus,eqnu=F,tol=1e-6,max.iter=2000,per=100)
  fit.rst.na4=MCrstFA.na.ECME(Y.na=Y.na4,initial=initial,true.clus=true.clus,eqnu=F,tol=1e-6,max.iter=2000,per=100)
  
  write(c(j, fit.n.na2$yhat.obs.new), paste(WD.PATH, 'results/Sim1_TabFig/mcfa.yhat.obs.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na2$post.clus), paste(WD.PATH, 'results/Sim1_TabFig/mcfa.clus.obs.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.t.na2$yhat.obs.new), paste(WD.PATH, 'results/Sim1_TabFig/mctfa.yhat.obs.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.t.na2$post.clus), paste(WD.PATH, 'results/Sim1_TabFig/mctfa.clus.obs.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.rst.na2$yhat.obs.new), paste(WD.PATH, 'results/Sim1_TabFig/mcrstfa.yhat.obs.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.rst.na2$post.clus), paste(WD.PATH, 'results/Sim1_TabFig/mcrstfa.clus.obs.txt', sep=''), ncol=10000, append=T)
  write(c(j, Y.na2), paste(WD.PATH, 'results/Sim1_TabFig/yna.txt', sep=''), ncol=10000, append=T)

  write(c(j, fit.n.na1$BIC, fit.t.na1$BIC, fit.rst.na1$BIC), paste(WD.PATH, 'results/Sim1_TabFig/bic1.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na1$ICL, fit.t.na1$ICL, fit.rst.na1$ICL), paste(WD.PATH, 'results/Sim1_TabFig/icl1.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na1$ARI, fit.t.na1$ARI, fit.rst.na1$ARI), paste(WD.PATH, 'results/Sim1_TabFig/ari1.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na1$CCR, fit.t.na1$CCR, fit.rst.na1$CCR), paste(WD.PATH, 'results/Sim1_TabFig/ccr1.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na1$MSE.new, fit.t.na1$MSE.new, fit.rst.na1$MSE.new), paste(WD.PATH, 'results/Sim1_TabFig/mspe1.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na2$BIC, fit.t.na2$BIC, fit.rst.na2$BIC), paste(WD.PATH, 'results/Sim1_TabFig/bic2.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na2$ICL, fit.t.na2$ICL, fit.rst.na2$ICL), paste(WD.PATH, 'results/Sim1_TabFig/icl2.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na2$ARI, fit.t.na2$ARI, fit.rst.na2$ARI), paste(WD.PATH, 'results/Sim1_TabFig/ari2.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na2$CCR, fit.t.na2$CCR, fit.rst.na2$CCR), paste(WD.PATH, 'results/Sim1_TabFig/ccr2.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na2$MSE.new, fit.t.na2$MSE.new, fit.rst.na2$MSE.new), paste(WD.PATH, 'results/Sim1_TabFig/mspe2.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na3$BIC, fit.t.na3$BIC, fit.rst.na3$BIC), paste(WD.PATH, 'results/Sim1_TabFig/bic3.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na3$ICL, fit.t.na3$ICL, fit.rst.na3$ICL), paste(WD.PATH, 'results/Sim1_TabFig/icl3.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na3$ARI, fit.t.na3$ARI, fit.rst.na3$ARI), paste(WD.PATH, 'results/Sim1_TabFig/ari3.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na3$CCR, fit.t.na3$CCR, fit.rst.na3$CCR), paste(WD.PATH, 'results/Sim1_TabFig/ccr3.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na3$MSE.new, fit.t.na3$MSE.new, fit.rst.na3$MSE.new), paste(WD.PATH, 'results/Sim1_TabFig/mspe3.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na4$BIC, fit.t.na4$BIC, fit.rst.na4$BIC), paste(WD.PATH, 'results/Sim1_TabFig/bic4.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na4$ICL, fit.t.na4$ICL, fit.rst.na4$ICL), paste(WD.PATH, 'results/Sim1_TabFig/icl4.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na4$ARI, fit.t.na4$ARI, fit.rst.na4$ARI), paste(WD.PATH, 'results/Sim1_TabFig/ari4.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na4$CCR, fit.t.na4$CCR, fit.rst.na4$CCR), paste(WD.PATH, 'results/Sim1_TabFig/ccr4.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na4$MSE.new, fit.t.na4$MSE.new, fit.rst.na4$MSE.new), paste(WD.PATH, 'results/Sim1_TabFig/mspe4.txt', sep=''), ncol=10000, append=T)
}

#rMSL
for(j in 1:m)
{
  Y=NULL
  for(i in 1:g)
  {
    Y <- rbind(Y, rMSL(n, mu[,i], sig[,,i], alpha[,i]))
  }
  initial=init.para(Y=Y,g=g,q=q,true.clus=true.clus,init='CPC',init.clus=T,random.start=F)
  Y.na1=gener.na(Y,0.1)
  Y.na2=gener.na(Y,0.2)
  Y.na3=gener.na(Y,0.3)
  Y.na4=gener.na(Y,0.4)
  fit.n.na1=MCFA.na.ECME(Y.na=Y.na1,initial=initial,true.clus=true.clus,eqnu=F,tol=1e-6,max.iter=2000,per=100)
  fit.t.na1=MCtFA.na.ECME(Y.na=Y.na1,initial=initial,true.clus=true.clus,eqnu=F,tol=1e-6,max.iter=2000,per=100)
  fit.rst.na1=MCrstFA.na.ECME(Y.na=Y.na1,initial=initial,true.clus=true.clus,eqnu=F,tol=1e-6,max.iter=2000,per=100)
  fit.n.na2=MCFA.na.ECME(Y.na=Y.na2,initial=initial,true.clus=true.clus,eqnu=F,tol=1e-6,max.iter=2000,per=100)
  fit.t.na2=MCtFA.na.ECME(Y.na=Y.na2,initial=initial,true.clus=true.clus,eqnu=F,tol=1e-6,max.iter=2000,per=100)
  fit.rst.na2=MCrstFA.na.ECME(Y.na=Y.na2,initial=initial,true.clus=true.clus,eqnu=F,tol=1e-6,max.iter=2000,per=100)
  fit.n.na3=MCFA.na.ECME(Y.na=Y.na3,initial=initial,true.clus=true.clus,eqnu=F,tol=1e-6,max.iter=2000,per=100)
  fit.t.na3=MCtFA.na.ECME(Y.na=Y.na3,initial=initial,true.clus=true.clus,eqnu=F,tol=1e-6,max.iter=2000,per=100)
  fit.rst.na3=MCrstFA.na.ECME(Y.na=Y.na3,initial=initial,true.clus=true.clus,eqnu=F,tol=1e-6,max.iter=2000,per=100)
  fit.n.na4=MCFA.na.ECME(Y.na=Y.na4,initial=initial,true.clus=true.clus,eqnu=F,tol=1e-6,max.iter=2000,per=100)
  fit.t.na4=MCtFA.na.ECME(Y.na=Y.na4,initial=initial,true.clus=true.clus,eqnu=F,tol=1e-6,max.iter=2000,per=100)
  fit.rst.na4=MCrstFA.na.ECME(Y.na=Y.na4,initial=initial,true.clus=true.clus,eqnu=F,tol=1e-6,max.iter=2000,per=100)
  
  write(c(j, fit.n.na2$yhat.obs.new), paste(WD.PATH, 'results/Sim1_TabFig/mcfa.yhat.obs_msl.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na2$post.clus), paste(WD.PATH, 'results/Sim1_TabFig/mcfa.clus.obs_msl.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.t.na2$yhat.obs.new), paste(WD.PATH, 'results/Sim1_TabFig/mctfa.yhat.obs_msl.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.t.na2$post.clus), paste(WD.PATH, 'results/Sim1_TabFig/mctfa.clus.obs_msl.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.rst.na2$yhat.obs.new), paste(WD.PATH, 'results/Sim1_TabFig/mcrstfa.yhat.obs_msl.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.rst.na2$post.clus), paste(WD.PATH, 'results/Sim1_TabFig/mcrstfa.clus.obs_msl.txt', sep=''), ncol=10000, append=T)
  write(c(j, Y.na2), paste(WD.PATH, 'results/Sim1_TabFig/yna_msl.txt', sep=''), ncol=10000, append=T)
  
  write(c(j, fit.n.na1$BIC, fit.t.na1$BIC, fit.rst.na1$BIC), paste(WD.PATH, 'results/Sim1_TabFig/bic1_msl.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na1$ICL, fit.t.na1$ICL, fit.rst.na1$ICL), paste(WD.PATH, 'results/Sim1_TabFig/icl1_msl.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na1$ARI, fit.t.na1$ARI, fit.rst.na1$ARI), paste(WD.PATH, 'results/Sim1_TabFig/ari1_msl.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na1$CCR, fit.t.na1$CCR, fit.rst.na1$CCR), paste(WD.PATH, 'results/Sim1_TabFig/ccr1_msl.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na1$MSE.new, fit.t.na1$MSE.new, fit.rst.na1$MSE.new), paste(WD.PATH, 'results/Sim1_TabFig/mspe1_msl.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na2$BIC, fit.t.na2$BIC, fit.rst.na2$BIC), paste(WD.PATH, 'results/Sim1_TabFig/bic2_msl.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na2$ICL, fit.t.na2$ICL, fit.rst.na2$ICL), paste(WD.PATH, 'results/Sim1_TabFig/icl2_msl.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na2$ARI, fit.t.na2$ARI, fit.rst.na2$ARI), paste(WD.PATH, 'results/Sim1_TabFig/ari2_msl.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na2$CCR, fit.t.na2$CCR, fit.rst.na2$CCR), paste(WD.PATH, 'results/Sim1_TabFig/ccr2_msl.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na2$MSE.new, fit.t.na2$MSE.new, fit.rst.na2$MSE.new), paste(WD.PATH, 'results/Sim1_TabFig/mspe2_msl.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na3$BIC, fit.t.na3$BIC, fit.rst.na3$BIC), paste(WD.PATH, 'results/Sim1_TabFig/bic3_msl.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na3$ICL, fit.t.na3$ICL, fit.rst.na3$ICL), paste(WD.PATH, 'results/Sim1_TabFig/icl3_msl.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na3$ARI, fit.t.na3$ARI, fit.rst.na3$ARI), paste(WD.PATH, 'results/Sim1_TabFig/ari3_msl.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na3$CCR, fit.t.na3$CCR, fit.rst.na3$CCR), paste(WD.PATH, 'results/Sim1_TabFig/ccr3_msl.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na3$MSE.new, fit.t.na3$MSE.new, fit.rst.na3$MSE.new), paste(WD.PATH, 'results/Sim1_TabFig/mspe3_msl.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na4$BIC, fit.t.na4$BIC, fit.rst.na4$BIC), paste(WD.PATH, 'results/Sim1_TabFig/bic4_msl.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na4$ICL, fit.t.na4$ICL, fit.rst.na4$ICL), paste(WD.PATH, 'results/Sim1_TabFig/icl4_msl.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na4$ARI, fit.t.na4$ARI, fit.rst.na4$ARI), paste(WD.PATH, 'results/Sim1_TabFig/ari4_msl.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na4$CCR, fit.t.na4$CCR, fit.rst.na4$CCR), paste(WD.PATH, 'results/Sim1_TabFig/ccr4_msl.txt', sep=''), ncol=10000, append=T)
  write(c(j, fit.n.na4$MSE.new, fit.t.na4$MSE.new, fit.rst.na4$MSE.new), paste(WD.PATH, 'results/Sim1_TabFig/mspe4_msl.txt', sep=''), ncol=10000, append=T)
}