xi_sd_n1=apply(xi_n1,2,sd)
xi_sd_n2=apply(xi_n2,2,sd)
xi_sd_n3=apply(xi_n3,2,sd)
la_sd_n1=apply(la_n1,2,sd)
la_sd_n2=apply(la_n2,2,sd)
la_sd_n3=apply(la_n3,2,sd)
Om_sd_n1=apply(Om_n1,2,sd)
Om_sd_n2=apply(Om_n2,2,sd)
Om_sd_n3=apply(Om_n3,2,sd)
w_sd_n1=apply(w_n1,2,sd)
w_sd_n2=apply(w_n2,2,sd)
w_sd_n3=apply(w_n3,2,sd)
nu_sd_n1=apply(nu_n1,2,sd)
nu_sd_n2=apply(nu_n2,2,sd)
nu_sd_n3=apply(nu_n3,2,sd)
A_sd_n1=apply(A_n1,2,sd)
A_sd_n2=apply(A_n2,2,sd)
A_sd_n3=apply(A_n3,2,sd)
D_sd_n1=apply(D_n1,2,sd)
D_sd_n2=apply(D_n2,2,sd)
D_sd_n3=apply(D_n3,2,sd)

xi_sd_n1=matrix(xi_sd_n1,q,g)
la_sd_n1=matrix(la_sd_n1,q,g)
Om_sd_n1=array(Om_sd_n1, dim=c(q,q,g))
A_sd_n1=matrix(A_sd_n1,p,q)
D_sd_n1=matrix(D_sd_n1,p,p)
xi_sd_n2=matrix(xi_sd_n2,q,g)
la_sd_n2=matrix(la_sd_n2,q,g)
Om_sd_n2=array(Om_sd_n2, dim=c(q,q,g))
A_sd_n2=matrix(A_sd_n2,p,q)
D_sd_n2=matrix(D_sd_n2,p,p)
xi_sd_n3=matrix(xi_sd_n3,q,g)
la_sd_n3=matrix(la_sd_n3,q,g)
Om_sd_n3=array(Om_sd_n3, dim=c(q,q,g))
A_sd_n3=matrix(A_sd_n3,p,q)
D_sd_n3=matrix(D_sd_n3,p,p)


